name: Format Code

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config user.name "davidgarciamt"
          git config user.email "david.garcia@softwaresolutionssouthwest.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Update local main
        run: git checkout main && git pull origin main

      - name: Generate timestamp
        id: vars
        run: echo "BRANCH_SUFFIX=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create and switch to new branch
        run: git checkout -b auto/code-formatting-${{ env.BRANCH_SUFFIX }}

      - name: Run Prettier to format code
        run: npx prettier --write "**/*.{js,json,html,css}"

      - name: Stage changes
        run: |
          git add . -- :/ ':!package-lock.json'
          git reset package-lock.json

      - name: Commit changes
        run: |
          git commit -m "Apply Prettier formatting main" || echo "No changes to commit"
          git branch
          git rev-parse --abbrev-ref HEAD

      - name: Push branch
        run: |
          git push origin auto/code-formatting-${{ env.BRANCH_SUFFIX }}

      - name: Create Pull Request
        run: |
          gh pr create --base main --head auto/code-formatting-${{ env.BRANCH_SUFFIX }} --title "Apply Prettier formatting to main" --body "Automated formatting to main"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}